services:
  postgres:
    container_name: fazenda
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fazenda
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
